feat: try new script
Stable and working. Wait 30 mins for job to finish or break early

diff --git a/.github/workflows/gh-smoke-test-executer.yml b/.github/workflows/gh-smoke-test-executer.yml
--- a/.github/workflows/gh-smoke-test-executer.yml
+++ b/.github/workflows/gh-smoke-test-executer.yml
@@ -77,13 +77,13 @@ jobs:
           if [ "${{ env.SMOKE_TEST_TYPE }}" == "dbs_batch_search" ]; then
             file_name="./tests/E2E.Tests/Resources/Smoke/dbs_batch_search_responses.txt"
             log_success_message="The DBS results file has 7 records, batch search resulted"
-            packagename = "SUI.DBS.Response.Logger.Watcher"
+            packagename="SUI.DBS.Response.Logger.Watcher"
             destinationpathfile="dbs_batch_search_responses.txt"
             logFilePrefix="dbs-response-logger-logs"
             executable="suidbsw.exe"
           else
             file_name="./tests/E2E.Tests/Resources/Smoke/sui_batch_search_queries.csv"
-            log_success_message="File processed; output=SUI.Client.Core.ProcessCsvFileResult"
+            log_success_message="Finished processing file: sui_batch_search_queries.csv"
             packagename="SUI.Client.Watcher"
             destinationpathfile="sui_batch_search_queries.csv"
             logFilePrefix="sui-client-logs"
@@ -103,8 +103,8 @@ jobs:
           echo "data<<${EOF}" >> $GITHUB_OUTPUT
           base_64=`openssl base64 -in ${{ env.file_name }}` ; echo "${base_64}" >> $GITHUB_OUTPUT
           echo "${EOF}" >> $GITHUB_OUTPUT
-
-      - name: Smoke Test Run (.exe)
+          
+      - name: Smoke Test Run (tool)
         id: return_data
         run: |
           return_data="$(az vm run-command invoke \
@@ -113,106 +113,93 @@ jobs:
             --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
             --script '
 
-          $packageName="${{ env.packagename }}"
-          $destinationPathFile="${{ env.destinationpathfile }}"
           $basePath = "C:\Users\SmokeTests"
+          $serverUrl = "${{ env.SUI_SERVER_URL }}"
+          $installPath = "C:\Program Files\dotnet\tools"
           $basePathUnprocessed = "$basePath\unprocessed"
           $basePathProcessed = "$basePath\processed"
+          $packageName="${{ env.packagename }}"
+          $destinationPathFile="${{ env.destinationpathfile }}"
           $destinationPath = "$basePathUnprocessed\$destinationPathFile"
-          $installPath = "C:\Program Files\dotnet\tools"
+          $logFileName = "sui-client-logs-$(Get-Date -Format 'yyyy-MM-dd').log"
+          $logFilePath = Join-Path $basePath $logFileName
+          # 30 minutes timeout for the tool to run should be enough for most smoke tests
+          $toolTimeoutInSeconds = 1800
 
-          function Clean-SmokeTestEnvironment {
-              param (
-            [string]$SmokeTestsPath,
-            [string]$PackageName
-              )
-              # Check for the existence of the directory and clean it up if it exists
-              if (Test-Path $SmokeTestsPath) {
-            Remove-Item -Path $SmokeTestsPath -Recurse -Force
-              }
-              # Check for the dotnet package and remove it if it exists
-              if (dotnet tool list --tool-path $installPath | Select-String $PackageName) {
-            dotnet tool uninstall --tool-path $installPath $PackageName
-              }
+          function Cleanup-SmokeTestEnvironment {
+            param([string]$PackageName, [string]$SmokeTestsPath)
+            dotnet tool uninstall $PackageName --tool-path $installPath
+            if (Test-Path $SmokeTestsPath) { Remove-Item -Path $SmokeTestsPath -Recurse -Force }
           }
 
-          Clean-SmokeTestEnvironment -SmokeTestsPath $basePath -PackageName $packageName
-          # Install the package
+          Cleanup-SmokeTestEnvironment -PackageName $packageName -SmokeTestsPath $basePath
+
           dotnet tool install $packageName --tool-path $installPath
-          # Check if tool path in PATH and add it if not
+
           if ($env:Path -notlike "*$installPath*") {
-              Write-Output "Adding $installPath to PATH"
-              $env:Path = "$installPath;$env:Path"
+            $env:Path = "$installPath;$env:Path"
           }
 
-          # Create the SmokeTests directories
           New-Item -ItemType Directory -Path $basePath -Force
           New-Item -ItemType Directory -Path $basePathUnprocessed -Force
           New-Item -ItemType Directory -Path $basePathProcessed -Force
 
-          # Start the smoke test executable in a background job
-
+          # Start tool in background using Start-Job
           if ("${{ env.SMOKE_TEST_TYPE }}" -eq "client_batch_search") {
-              $job = Start-Job -ScriptBlock {
-                  Param($basePath, $basePathUnprocessed, $basePathProcessed)
-                  cd $basePath;
-                  ${{ env.executable }} $basePathUnprocessed $basePathProcessed ${{ env.SUI_SERVER_URL }}
-                  } -ArgumentList $basePath, $basePathUnprocessed, $basePathProcessed
+            $job = Start-Job -ScriptBlock {
+                Param($basePath, $basePathUnprocessed, $basePathProcessed, $serverUrl)
+                cd $basePath;
+                & ${{ env.executable }} $basePathUnprocessed $basePathProcessed $serverUrl
+                } -ArgumentList $basePath, $basePathUnprocessed, $basePathProcessed, $serverUrl
           } else {
-              $job = Start-Job -ScriptBlock {
-                  Param($basePath, $basePathUnprocessed, $basePathProcessed)
-                  cd $basePath; 
-                  ${{ env.executable }} $basePathUnprocessed $basePathProcessed
-                  } -ArgumentList $basePath, $basePathUnprocessed, $basePathProcessed
+            $job = Start-Job -ScriptBlock {
+                Param($basePath, $basePathUnprocessed, $basePathProcessed)
+                cd $basePath; 
+                & ${{ env.executable }} $basePathUnprocessed $basePathProcessed
+                } -ArgumentList $basePath, $basePathUnprocessed, $basePathProcessed
           }
 
+          # Give time for the job to start before writing the file
+          Start-Sleep -Seconds 30
 
           $fileContent = "${{ steps.read_file.outputs.data }}"
-
           [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("$fileContent")) | Out-File -FilePath $destinationPath -Encoding utf8
 
-          # Poll log file until it hasnt been updated for 1 minute
-          $today = Get-Date -Format "yyyy-MM-dd"
-          $logFilePrefix = "${{ env.logFilePrefix }}-$today.log"
-          $logFile = "$basePath\$logFilePrefix"
-          $lastWriteTime = (Get-Item $logFile).LastWriteTime
-          $timeout = (Get-Date).AddMinutes(5)
-          $unchangedCount = 0
-
-          $logfiletimeout = (Get-Date).AddMinutes(1)
-          while ((Get-Date) -lt $logfiletimeout -and !(Test-Path $logFile)) {
-              Start-Sleep -Seconds 2
-          }
-
-          if (!(Test-Path $logFile)) {
-              Write-Error "Log file was not created in time."
-          }
+          $timeout = (Get-Date).AddSeconds($toolTimeoutInSeconds)
+          $successFound = $false
 
           while ((Get-Date) -lt $timeout) {
-              Start-Sleep -Seconds 5
-              $currentWriteTime = (Get-Item $logFile).LastWriteTime
-              if ($currentWriteTime -eq $lastWriteTime) {
-                  $unchangedCount++
-                  if ($unchangedCount -ge 2) { break }
-              } else {
-                  $unchangedCount = 0
-                  $lastWriteTime = $currentWriteTime
+            if (Test-Path $logFilePath) {
+              $logContent = Get-Content -Path $logFilePath -Raw
+              if ($logContent -match "${{ env.log_success_message }}") {
+                Write-Output "Smoke Test Passed"
+                $successFound = $true
+                break
               }
+            }
+            Start-Sleep -Seconds 2
           }
-          # Save log file content to a variable
-          $logContent = Get-Content -Path $logFile -Raw
 
-          # Assert smoke test was successful
-          if ($logContent -match "${{ env.log_success_message }}") {
-              Write-Output "Smoke Test Passed"
-              Stop-Job $job
-              Clean-SmokeTestEnvironment -SmokeTestsPath $basePath -PackageName $packageName
-              exit 0 # Exit with a zero status code
-          } else {
-              Write-Error "Smoke Test Failed"
-              Stop-Job $job
-              exit 1 # Exit with a non-zero status code
+          # Ensure the background job completes or is stopped
+          $jobTimeout = 60
+          Wait-Job -Job $job -Timeout $jobTimeout | Out-Null
+
+          if ($job.State -eq "Running") {
+            Stop-Job -Job $job
           }
+
+          Receive-Job -Job $job
+          Remove-Job -Job $job
+
+          if (-not $successFound) {
+            Write-Error "Smoke Test Failed"
+            exit 1
+          }
+          else {
+           Cleanup-SmokeTestEnvironment -PackageName $packageName -SmokeTestsPath $basePath
+          }
+
+          exit 0
           ')"
           EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
           echo "return_data<<${EOF}" >> $GITHUB_OUTPUT
