bugfix: sui-399 - improving error handling in smoke tests

diff --git a/.github/workflows/gh-smoke-test.yml b/.github/workflows/gh-smoke-test.yml
--- a/.github/workflows/gh-smoke-test.yml
+++ b/.github/workflows/gh-smoke-test.yml
@@ -113,8 +113,9 @@ jobs:
             
         - name: Smoke Test DBS Response Logger (.exe)
           if: ((env.triggered_workflow == 'Build and Upload DBS Response Logger Watcher') || (env.cron_run == 'true'))
+          id: dbs_return_data
           run: |
-            az vm run-command invoke \
+            dbs_return_data="$(az vm run-command invoke \
               --command-id RunPowerShellScript \
               --name ${{ secrets.VM_NAME }} \
               --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
@@ -151,12 +152,28 @@ jobs:
                 Write-Error "Smoke Test Failed"
                 exit 1 # Exit with a zero status code
               }
-              '
+              ')"
+              EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
+              echo "dbs_return_data<<${EOF}" >> $GITHUB_OUTPUT
+              echo "${dbs_return_data}" >> $GITHUB_OUTPUT
+              echo "${EOF}" >> $GITHUB_OUTPUT
+        
+        - name: check contents of return data for exceptions and errors
+          if: ((env.triggered_workflow == 'Build and Upload DBS Response Logger Watcher') || (env.cron_run == 'true'))
+          run: |
+            echo "Return data: ${{ steps.dbs_return_data.outputs.dbs_return_data }}"
+            if [[ "${{ steps.dbs_return_data.outputs.dbs_return_data }}" == *"Exception"* || "${{ steps.dbs_return_data.outputs.dbs_return_data }}" == *"Error"* ]]; then
+              echo "Smoke Test Failed"
+              exit 1
+            else
+              echo "Smoke Test Passed"
+            fi
             
         - name: Smoke Test SUI Client (.exe)
           if: ((env.triggered_workflow == 'Azure App Deployment' || env.triggered_workflow == 'Build and Upload Client Watcher') || (env.cron_run == 'true'))
+          id: client_return_data
           run: |
-            az vm run-command invoke \
+            client_return_data="$(az vm run-command invoke \
               --command-id RunPowerShellScript \
               --name ${{ secrets.VM_NAME }} \
               --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
@@ -201,4 +218,19 @@ jobs:
                 Write-Error "Smoke Test Failed"
                 exit 1 # Exit with a zero status code
               }
-              '
+              ')"
+              EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
+              echo "client_return_data<<${EOF}" >> $GITHUB_OUTPUT
+              echo "${client_return_data}" >> $GITHUB_OUTPUT
+              echo "${EOF}" >> $GITHUB_OUTPUT
+
+        - name: check contents of return data for exceptions and errors
+          if: ((env.triggered_workflow == 'Azure App Deployment' || env.triggered_workflow == 'Build and Upload Client Watcher') || (env.cron_run == 'true'))
+          run: |
+            echo "Return data: ${{ steps.client_return_data.outputs.client_return_data }}"
+            if [[ "${{ steps.client_return_data.outputs.client_return_data }}" == *"Exception"* || "${{ steps.client_return_data.outputs.client_return_data }}" == *"Error"* ]]; then
+              echo "Smoke Test Failed"
+              exit 1
+            else
+              echo "Smoke Test Passed"
+            fi
